package constants;

import java.util.ArrayList;
import java.util.Arrays;

public class LookUpConstants2 {

    static ArrayList<String> languages = new ArrayList<>(Arrays.asList(
            "Albanian",
            "Arabic",
            "Armenian",
            "Azerbaijani",
            "Bosnian",
            "Bulgarian",
            "Croatian",
            "Czech",
            "Danish",
            "Dutch",
            "English",
            "Estonian",
            "Farsi",
            "Finnish",
            "French",
            "Georgian",
            "German",
            "Greek",
            "Hebrew",
            "Hindi",
            "Hungarian",
            "Icelandic",
            "Indonesian",
            "Italian",
            "Japanese",
            "Kazakh",
            "Korean",
            "Kyrgyz",
            "Latvian",
            "Lithuanian",
            "Macedonian",
            "Malay",
            "Mandarin",
            "Moldavian",
            "Norwegian",
            "Polish",
            "Portuguese",
            "Romanian",
            "Russian",
            "Serbian",
            "Slovak",
            "Slovenian",
            "Spanish",
            "Swedish",
            "Tadjik",
            "Taglish",
            "Thai",
            "Turkmen",
            "Ukrainian",
            "Uzbek",
            "Vietnamese",
            "Turkish",
            "Flemish",
            "Cantonese",
            "Chinese Simplified",
            "Chinese Traditional"
    ));

    static ArrayList<String> customerSpecific = new ArrayList<>(Arrays.asList(
            "JD",
            "Tmall",
            "Amazon",
            "Target",
            "Costco",
            "Walmart",
            "HealthPets",
            "Petco",
            "Kroger",
            "Woolworths",
            "Chewy",
            "Loblaws",
            "Sams Club",
            "Coles",
            "N/A"
    ));
    static ArrayList<String> rightsRestricted = new ArrayList<>(Arrays.asList(
            "Yes",
            "No"));
    static ArrayList<String> rightsManagementType = new ArrayList<>(Arrays.asList(
            "AVO",
            "Image Rights",
            "Music License",
            "Musicians",
            "On-Camera Talent/Model"
    ));
    static ArrayList<String> MasterOrLocalised = new ArrayList<>(Arrays.asList(
            "Master File",
            "Localized File",
            "Adapted File"
    ));
    static ArrayList<String> PetLifeStage = new ArrayList<>(Arrays.asList(
            "All",
            "Adult",
            "Senior",
            "Kitten",
            "Puppy",
            "N/A"
    ));
    static ArrayList<String> PetSizes = new ArrayList<>(Arrays.asList(
            "Small",
            "Medium",
            "Large",
            "Mini",
            "Regular",
            "Small Medium",
            "Medium Large",
            "Extra Large",
            "N/A"
    ));
    static ArrayList<String> healthBenefits = new ArrayList<>(Arrays.asList(
            "Small",
            "Medium",
            "Large",
            "Mini",
            "Regular",
            "Small Medium",
            "Medium Large",
            "Extra Large",
            "N/A"
    ));

    static ArrayList<String> species = new ArrayList<>(Arrays.asList(
            "Cat",
            "Dog",
            "Rabbit" ));


    static ArrayList<String> displayPackTypes = new ArrayList<>(Arrays.asList(
            "Stand Up Pouch", "Shipper", "Tub", "Shipper - Product as It Ships", "Shipper - Product Inside Box",
            "Shipper - Product Outside Box", "Multi-Wall Bag", "Polybag", "Can", "Displayable Cases/Trays",
            "Carton", "Box", "Gravity Display", "Flowwrap", "Tube", "Pouch", "Shrink Wrap", "Tray", "Bag",
            "Shipping Case", "Blister Pack", "Sleeve", "Backer Card", "Display Ready Tray", "Stand Up Bag",
            "MultiPack", "Lid", "Base", "Wrapper", "Tin Shrink Wrap", "Seasonal Overwrap", "Outer Shrink Wrap",
            "Bag - Paper", "Bottle", "Clip Strip", "Blister Card", "Holiday Pack", "Pack", "Pot",
            "Re-closable Packaging", "Metal Tin", "Laydown Bag", "Display Ready Case", "Tray Base", "Tray Lid",
            "Shrink Wrap Tin", "Packet", "Floorstand", "Label", "Can Label", "Tower Display", "Pallet Display",
            "Flowwrap Bag", "Half Pallet", "Peg Bag", "Plastic Pack", "Flowbag", "Flowwrap Single Stick", "Cup",
            "Gift Box", "Bag - Plastic", "Sachet", "Tin", "Tray Display", "Stickers", "Tray Cover",
            "Shelf Ready Packaging", "Label Canister Wraparound", "N/A"
    ));

    static ArrayList<String> breeds = new ArrayList<>(Arrays.asList(
            "Abyssinian", "American Bobtail", "American Burmese", "American Curl", "American Longhair", "American Polydactyl",
            "American Shorthair", "American Wirehair", "Aphrodite Giant", "Arabian Mau", "Asian", "Australian Bombay",
            "Australian Mist", "Balinese", "Bambino", "Bengal", "Bombay", "Brazilian Shorthair", "British Longhair",
            "British Shorthair", "Burmese", "Burmilla", "California Spangled", "Californian Rex", "Celtic Shorthair",
            "Ceylan", "Chantilly Tiffany", "Chartreux", "Chausie", "Chinchilla Longhair", "Classicat", "Cornish Rex",
            "Cymric", "Devon Rex", "Domestic Lynx", "Don Sphynx", "Donskoy", "Egyptian Mau", "European", "European Burmese",
            "European Shorthair", "Exotic Shorthair", "German Rex", "Giant", "Havana", "Highland Straight", "Isle of Man",
            "Japanese Bobtail", "Khao Manee", "Korat", "Kurilian Bobtail", "LaPerm", "Lykoi", "Maine Coon", "Mandalay",
            "Manx", "Mau", "Medium", "Mixed Breed", "Mixed Breed Giant", "Mixed Breed Medium", "Mixed Breed XSmall",
            "Nebelung", "Neva Masquerade", "Norwegian Forest Cat", "Ocicat", "Oriental", "Oriental Shorthair", "Persian",
            "Peterbald", "Pixiebob", "RagaMuffin", "Ragdoll", "Russian", "Russian Blue", "Russie", "Sacred Birman",
            "Savannah", "Scottish", "Scottish Fold", "Selkirk", "Selkirk Rex", "Seychellois", "Siamese", "Siberian",
            "Siberian Colourpoint", "Singapura", "Small", "Snowshoe", "Sokoke", "Somali", "Sphynx", "Suffolk Cat", "Thai",
            "Tonkinese", "Turkish Angora", "Turkish Van", "Undefined", "Undefined Giant", "Vankedisi", "XSmall",
            "Affenpinscher", "Akbash Dog", "Akita", "Alaskan Husky", "Alaskan Klee Kai", "Alaskan Malamute",
            "American Bulldog", "American Bully", "American Eskimo Dog", "American Hairless Terrier",
            "American Leopard Hound", "American Pit Bull Terrier", "American Staffordshire Terrier", "Anatoli",
            "Anatolian Shepherd", "Anglo Français de Petite Vénerie", "Anjing Kintamani-Bali", "Appenzell Cattle Dog",
            "Appenzeller Sennenhund", "Ariege Pointing Dog", "Ariegeois", "Artesian Norman Basset", "Artois Hound",
            "Atlas Mountain Dog (Aidi)", "Australian Cattle Dog", "Australian Kelpie", "Australian Shepherd",
            "Australian Silky Terrier", "Australian Stumpy Tail Cattle Dog", "Austrian Black and Tan Hound",
            "Austrian Pinscher", "Auvergne Pointer", "Azawakh", "Barbet", "Basenji", "Basset Artesien Normand",
            "Basset Bleu de Gascogne", "Basset Fauve de Bretagne", "Bavarian Mountain Hound", "Beagle Harrier",
            "Bearded Collie", "Belgian Groenendael Sheepdog", "Belgian Laekenois Sheepdog", "Belgian Malinois Sheepdog",
            "Belgian Sheepdog", "Bergamasco Shepherd Dog", "Berger Blanc Suisse", "Berger d'Auvergne", "Berger de Beauce",
            "Berger Picard", "Berner Sennenhund", "Bernese Mountain Dog", "Bichon à Poil Frisé", "Bichon Frise",
            "Bichon Frisé", "Bichon Havanais", "Black and Tan Coonhound", "Black Mouth Cur", "Bloodhound",
            "Bluetick Coonhound", "Bolognese", "Border Collie", "Border Terrier", "Bosanski Ostrodlaki Gonic-Barak",
            "Boston Terrier", "Bouledogue Français", "Bouvier des Ardennes", "Boxer", "Bracco Italiano",
            "Brandlbracke - (Vieräugl)", "Braque d'Auvergne", "Braque de l'Ariege", "Braque du Bourbonnais",
            "Braque Français - Type Gascogne", "Braque Français - Type Pyrenees", "Braque Saint-Germain",
            "Briquet de Provence", "Briquet Griffon Vendeen", "Brittany Spaniel", "Broholmer", "Brussels Griffon",
            "Bulldog", "Ca de Bestiar", "Cairn Terrier", "Canaan Dog", "Cane Corso", "Cane Corso Italiano",
            "Cane da Pastore Bergamasco", "Cane da Pastore Maremmano-Abruzzese", "Caniche", "Caniche Nain", "Caniche Toy",
            "Cão da Serra da Estrela", "Cão de Água Português", "Cão de Castro Laboreiro", "Cão Fila de São Miguel",
            "Carolina Dog", "Catahoula Leopard Dog", "Cavalier King Charles", "Cavalier King Charles Spaniel",
            "Ceskoslovenský Vlciak", "Ceský Fousek", "Ceský Terier", "Chart Polski", "Chesapeake Bay Retriever",
            "Chien d'Artois", "Chien de Berger Belge", "Chien de Berger des Pyrenees à Face Rase",
            "Chien de Berger des Pyrenees à Poil Long", "Chien de Montagne des Pyrenees", "Chien de Saint Hubert",
            "Chihuahua", "Chihuahueño", "Chihuahueno de Pelo Largo", "Chin", "Chinese Crested Dog", "Chinese Li Hua",
            "Chodksy Pes", "Chow Chow",       "Cimarron Uruguayo",
            "Ciobănesc Românesc Carpatin",
            "Ciobănesc Românesc de Bucovina",
            "Ciobănesc Românesc Mioritic",
            "Cirneco dell'Etna",
            "Clumber Spaniel",
            "Cockapoo",
            "Collie",
            "Collie Rough",
            "Collie Smooth",
            "Continental Bulldog",
            "Coonhound Redbone",
            "Coton de Tulear",
            "Crnogorski Planinski Gonic",
            "Curly Coated Retriever",
            "Dachshund",
            "Dachshund Long-haired",
            "Dachshund Long-haired Miniature",
            "Dachshund Long-haired Rabbit",
            "Dachshund Smooth-haired",
            "Dachshund Smooth-haired Miniature",
            "Dachshund Smooth-haired Rabbit",
            "Dachshund Wire-haired",
            "Dachshund Wire-haired Miniature",
            "Dachshund Wire-haired Rabbit",
            "Dalmatian",
            "Dalmatinski Pas",
            "Dandie Dinmont Terrier",
            "Danish Swedish Farmdog",
            "Dansk-Svensk Gardshund",
            "Deerhound",
            "Deutsch Drahthaar",
            "Deutsch Kurzhaar",
            "Deutsch Langhaar",
            "Deutsch Stichelhaar",
            "Deutsche Bracke",
            "Deutscher Boxer",
            "Deutscher Jagdterrier",
            "Deutscher Pinscher",
            "Deutscher Schäferhund",
            "Deutscher Spitz Klein",
            "Deutscher Spitz Mittel",
            "Deutscher Wachtelhund",
            "Doberman",
            "Doberman Pinscher",
            "Dobermann",
            "Dogo Argentino",
            "Dogue de Bordeaux",
            "Do-Khyi",
            "Drentsche Patrijshond",
            "Drever",
            "Drötzörü Magyar Vizsla",
            "Dunker",
            "English Bulldog",
            "English Cocker Spaniel",
            "English Coonhound",
            "English Foxhound",
            "English Pointer",
            "English Setter",
            "English Shepherd",
            "English Springer Spaniel",
            "English Toy Terrier",
            "Entlebucher Sennenhund",
            "Epagneul Bleu de Picardie",
            "Epagneul Breton",
            "Epagneul de Pont-Audemer",
            "Epagneul Français",
            "Epagneul Nain Continental",
            "Epagneul Nain Continental Papillon",
            "Epagneul Picard",
            "Erdélyi Kopó",
            "Eurasier",
            "Field Spaniel",
            "Fila Brasileiro",
            "Finnish Hound",
            "Flat Coated Retriever",
            "Fox Terrier (Smooth)",
            "Fox Terrier (Wire)",
            "Français Blanc et Noir",
            "Français Blanc et Orange",
            "Français Tricolore",
            "French Bulldog",
            "French Spaniel",
            "Galgo Español",
            "Gammel Dansk Hønsehund",
            "German Pinscher",
            "German Shepherd",
            "German Shorthaired Pointer",
            "German Short-Haired Pointer",
            "German Wire-Haired Pointer",
            "Giant Schnauzer",
            "Glen of Imaal Terriers",
            "Golden Retriever",
            "Goldendoodle",
            "Gonczy Polski",
            "Gordon Setter",
            "Gos d'Atura Catalá",
            "Gotlan Hound",
            "Grand Anglo-Français Blanc et Noir",
            "Grand Anglo-Français Blanc et Orange",
            "Grand Anglo-Français Tricolore",
            "Grand Basset Griffon Vendeen",
            "Grand Bleu de Gascogne",
            "Grand Gascon Saintongeois",
            "Grand Griffon Vendeen",
            "Great Dane",
            "Greyhound",
            "Griffon à Poil Dur Korthals",
            "Griffon Belge",
            "Griffon Bleu de Gascogne",
            "Griffon Bruxellois",
            "Griffon Fauve de Bretagne",
            "Griffon Nivernais",
            "Grønlandshund",
            "Grosser Münsterländer Vorstehhund",
            "Grosser Schweizer Sennenhund",
            "Halden Hound",
            "Haldenstøver",
            "Hamiltonstövare",
            "Hannoverscher Schweisshund",
            "Harrier",
            "Havanese",
            "Hellinikos Ichnilatis",
            "Hokkaido",
            "Hollandse Herdershond",
            "Hollandse Smoushond",
            "Hovawart",
            "Hrvatski Ovcar",
            "Husky",
            "Hygen Hound",
            "Hygenhund",
            "Icelandic Sheepdog",
            "Irish Glen of Imaal Terrier",
            "Irish Red and White Setter",
            "Irish Red Setter",
            "Irish Setter",
            "Irish Soft Coated Wheaten Terrier",
            "Irish Terrier",
            "Irish Water Spaniel",
            "Irish Wolfhound",
            "Íslenskur Fjárhundur",
            "Istarski Kradkodlaki Gonic",
            "Istarski Ostrodlaki Gonic",
            "Italian Greyhound",
            "Jack Russel Terrier",
            "Jack Russell Terrier",
            "Jämthund",
            "Jugoslovenski Ovcarski Pas-Sarplaninac",
            "Kai",
            "Kangal Coban Köpegi",
            "Kangal Shepherd Dog",
            "Kaninchen",
            "Karjalankarhukoira",
            "Kavkazskaïa Ovtcharka",
            "Kerry Blue Terrier",
            "King Charles Spaniel",
            "Kishu",
            "Kleiner Münsterländer",
            "Komondor",
            "Korea Jindo Dog",
            "Kraski Ovcar",
            "Kromfohrländer",
            "Kuvasz",
            "Labradoodle",
            "Labrador",
            "Labrador Husky",
            "Labrador Retriever",
            "Lagotto Romagnolo",  "Lakeland Terrier",
            "Lancashire Heeler",
            "Landseer (Europäisch-Kontinentaler Typ)",
            "Lapinporokoira",
            "Leonberg",
            "Leonberger",
            "Lhasa Apso",
            "Little Lion Dog",
            "Magyar Agar",
            "Malamute",
            "Maltese",
            "Manchester Terrier",
            "Mastiff",
            "Mastín del Pirineo",
            "Mastín Español",
            "Mastino Napoletano",
            "Medium",
            "Miniature Bull Terrier",
            "Miniature Continental Papillon Spaniel",
            "Miniature Pinscher",
            "Miniature Schnauzer",
            "Mixed Breed",
            "Mixed Breed Giant",
            "Mixed Breed Maxi",
            "Mixed Breed Medium",
            "Mixed Breed Mini",
            "Mixed Breed XSmall",
            "Mudi",
            "Nederlandse Kooikerhondje",
            "Nederlandse Schapendoes",
            "Newfoundland",
            "Nihon Supittsu",
            "Nihon Teria",
            "Norfolk Terrier",
            "Norrbottenspets",
            "Norsk Buhund",
            "Norsk Elghund Grå",
            "Norsk Elghund Sort",
            "Norsk Lundehund",
            "Norwegian Buhund",
            "Norwich Terrier",
            "Nova Scotia Duck Tolling Retriever",
            "Ogar Polski",
            "Old English Bulldog",
            "Old English Sheepdog",
            "Otterhound",
            "Papillon",
            "Parson Russell Terrier",
            "Pekinese",
            "Pekingese",
            "Perdigueiro Portugués",
            "Perdiguero de Burgos",
            "Perro de Agua Español",
            "Perro Dogo Mallorquín",
            "Perro Sin Pelo del Perú",
            "Petit Basset Griffon Vendeen",
            "Petit Bleu de Gascogne",
            "Petit Brabançon",
            "Petit Chien Lion",
            "Petit Gascon Saintongeois",
            "Pharaoh Hound",
            "Picardy Sheepdog",
            "Piccolo Levriero Italiano",
            "Pinscher",
            "Podenco Canario",
            "Podenco Ibicenco",
            "Podengo Português",
            "Poitevin",
            "Polski Owczarek Podhalanski",
            "Polski Owzarek Nizinny",
            "Pomeranian",
            "Poodle",
            "Poodle Miniature",
            "Poodle Multi-colored",
            "Poodle Toy",
            "Porcelaine",
            "Portuguese Podengo Grande",
            "Posavski Gonic",
            "Prazsky Krysarik",
            "Presa Canario",
            "Pudelpointer",
            "Pug",
            "Puli",
            "Pumi",
            "Pyrenean Shepherd",
            "Rafeiro do Alentejo",
            "Rat Terrier",
            "Rhodesian Ridgeback",
            "Riesenschnauzer",
            "Romanian Mioritic Shepherd",
            "Rottweiler",
            "Rövidszörü Magyar Vizsla",
            "Russian Spaniel",
            "Russkaya Psovaya Borzaya",
            "Russkiy Tchiorny Terrier",
            "Russkiy Toy",
            "Russko-Evropeïskaïa Laïka",
            "Saarloos Wolfhound",
            "Saarlooswolfhond",
            "Sabueso Español",
            "Saint Bernard",
            "Saluki",
            "Samoiedskaïa Sabaka",
            "Samoyed",
            "Schillerstövare",
            "Schipperke",
            "Schnauzer",
            "Schweizer Laufhund - Chien Courant Suisse",
            "Schweizer Niederlaufhund - Petit Chien Courant Suisse",
            "Schweizer Schwyzer Laufhund - Chien Courant Schwyz",
            "Scottish Terrier",
            "Sealyham Terrier",
            "Segugio Italiano",
            "Segugio Italiano a Pelo Forte",
            "Segugio Italiano a Pelo Raso",
            "Segugio Maremmano",
            "Serbian Tricolour Hound",
            "Shar Pei",
            "Shetland Sheepdog",
            "Shiba",
            "Shiba Inu",
            "Shih Tzu",
            "Shikoku",
            "Siberian Husky",
            "Skye Terrier",
            "Sloughi",
            "Slovenský Cuvac",
            "Slovenský Hrubosrstý Stavač (Ohar)",
            "Slovenský Kopov",
            "Smålandsstövare",
            "Small",
            "Small Munsterlander",
            "Spanish Water Dog",
            "Spinone Italiano",
            "Spitz",
            "Sredneasiatskaya Ovtcharka",
            "Srpski Gonic",
            "Srpski Trobojni Gonic",
            "St Bernhardshund Shorthaired- Bernhardiner Shorthaired",
            "Stabijhoun",
            "Staffordshire Bull Terrier",
            "Steirische Rauhhaarbracke",
            "Suomenajokoira",
            "Suomenlapinkoira",
            "Suomenpystykorva",
            "Sussex Spaniel",
            "Svensk Lapphund",
            "Swedish Elkhound",
            "Taiwan Dog",
            "Terrier Brasileiro",
            "Thai Bangkaew Dog",
            "Thai Ridgeback Dog",
            "Tibetan Mastiff",
            "Tibetan Spaniel",
            "Tibetan Terrier",
            "Tiroler Bracke",
            "Tornjak",
            "Tosa",
            "Tyrolean Hound",
            "Undefined",
            "Undefined Giant",
            "Västgotaspets",
            "Vizsla",
            "Volpino Italiano",
            "Vostotchno-Sibirskaïa Laïka",
            "Weimarana",
            "Weimaraner",
            "Welsh Corgi Cardigan",
            "Welsh Springer Spaniel",
            "Welsh Terrier",
            "West Highland White Terrier",
            "West Highland White Terrier (Westie)",
            "West Siberian Laika",
            "Westfälische Dachsbracke",
            "Wetterhoun","Whippet",
            "Wolfsspitz",
            "Xoloitzcuintle",
            "XSmall",
            "Yakutskaya Laika",
            "Yorkshire Terrier",
            "Yuzhnorusskaya Ovcharka",
            "Zapadno-Sibirskaïa Laïka",
            "Zwergpinscher",
            "N/A"));


    static ArrayList<String> GlobalRegionalLocal = new ArrayList<>(Arrays.asList(
            "Global",
            "Regional",
            "Local",
            "Europe",
            "North America",
            "Asia Pacific",
            "Latin America",
            "Middle East & Africa"
    ));

    static ArrayList<String> OccasionyYears = new ArrayList<>(Arrays.asList(
            "2015",
            "2016",
            "2017",
            "2018",
            "2019",
            "2020",
            "2021",
            "2022",
            "2023",
            "2024",
            "2025",
            "N/A"
    ));

    public static ArrayList<String> getLanguages() {
        return languages;
    }

    public static  ArrayList<String> getCustomerSpecific() {
        return customerSpecific;
    }

    public static ArrayList<String> getRightsRestricted() {
        return rightsRestricted;
    }

    public static ArrayList<String> getRightsManagementType() {
        return rightsManagementType;
    }

    public static ArrayList<String> getMasterOrLocalised() {
        return MasterOrLocalised;
    }

    public static ArrayList<String> getPetLifeStage() {
        return PetLifeStage;
    }

    public static ArrayList<String> getPetSizes() {
        return PetSizes;
    }

    public static ArrayList<String> getHealthBenefits() {
        return healthBenefits;
    }

    public static ArrayList<String> getSpecies() {
        return species;
    }

    public static ArrayList<String> getDisplayPackTypes() {
        return displayPackTypes;
    }

    public static ArrayList<String> getBreeds() {
        return breeds;
    }

    public static ArrayList<String> getGlobalRegionalLocal() {
        return GlobalRegionalLocal;
    }

    public static ArrayList<String> getOccasionyYears() {
        return OccasionyYears;
    }

    public static ArrayList<String> getOccasion() {
        return Occasion;
    }

    public static ArrayList<String> getAssetStatus() {
        return assetStatus;
    }

    static ArrayList<String> Occasion = new ArrayList<>(Arrays.asList(
            "Back To School",
            "Christmas",
            "Dental Health Month",
            "Easter",
            "Fall",
            "Fathers Day",
            "Halloween",
            "Holiday",
            "Limited Edition",
            "Mothers Day",
            "NFL",
            "New Year",
            "Promotional",
            "Red, White, & Blue",
            "Seasonal",
            "Spring",
            "Summer",
            "Super Bowl",
            "Valentines Day",
            "CNY",
            "Winter"
    ));
    static ArrayList<String> assetStatus = new ArrayList<>(Arrays.asList(
            "In Revisions",
            "Approved",
            "Embargoed",
            "Expired",
            "Archived"
    ));
}
