package constants;

import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;

public class LookupConstants {

    public static List<String> getFlavorNames() {return flavorNames;}

    private static List<String> flavorNames = new ArrayList<>(Arrays.asList(
            "Apple", "Bacon", "Bacon and Beef", "Bacon and Egg", "Bacon and Filet Mignon",
            "Bacon, Egg, and Cheese", "Banana", "BBQ Chicken", "Beef", "Beef and Bacon",
            "Beef and Barley", "Beef and Cheese", "Beef and Chicken", "Beef and Liver",
            "Beef and Potato", "Beef and Rice", "Beef and Salmon", "Beef and Stew",
            "Beef and Vegetable", "Beef and Vegetables", "Beef Stew", "Beef Stroganoff",
            "Beef, Bacon, and Cheese", "Beef, Bacon, and Chicken", "Beef, Broccoli, and Brown Rice",
            "Beef, Cheese, and Bacon", "Beef, Chicken, and Liver", "Beef, Chicken, and Salmon",
            "Beef, Filet Mignon, Chicken, and Steak", "Beef, Milk, Vegetables, and Cereals",
            "Beef, Noodles, and Vegetables", "Beef, Rice, and Cheese", "Blend", "Blueberry",
            "Braised Rib", "Catfish and Tuna", "Catnip", "Catnip and Chicken", "Catnip, Tuna, and Dairy",
            "Cheese", "Cheese and Ham", "Cheeseburger", "Cheesy Chicken", "Cheesy Chicken Pasta",
            "Chef Inspired Chicken Entrée", "Chicken", "Chicken and Salmon", "Chicken & Parsley",
            "Chicken and Barley", "Chicken and Beef", "Chicken and Beef Stew", "Chicken and Carrot",
            "Chicken and Catfish", "Chicken and Cheddar", "Chicken and Cheese", "Chicken and Chickpeas",
            "Chicken and Egg", "Chicken and Filet Mignon", "Chicken and Lamb", "Chicken and Lentils",
            "Chicken and Liver", "Chicken and Mint", "Chicken and Oatmeal", "Chicken and Ocean Fish",
            "Chicken and Parsley", "Chicken and Pea", "Chicken and Potato", "Chicken and Rice",
            "Chicken and Salmon", "Chicken and Seafood", "Chicken and Shrimp", "Chicken and Tuna",
            "Chicken and Turkey", "Chicken and Turkey Casserole", "Chicken and Veal", "Chicken and Vegetable",
            "Chicken and Vegetables", "Chicken Rice and Lamb Rice", "Chicken, Bacon, and Cheese",
            "Chicken, Beef, and Lamb", "Chicken, Beef, and Liver", "Chicken, Beef, and Rice",
            "Chicken, Beef, and Turkey", "Chicken, Carrots, and Greens", "Chicken, Catnip, and Cheddar",
            "Chicken, Catnip, and Cheese", "Chicken, Egg, and Salmon", "Chicken, Fish, and Vegetables",
            "Chicken, Lamb, and Rice", "Chicken, Lamb, and Salmon", "Chicken, Lamb, Turkey & Salmon",
            "Chicken, liver & shrimp", "Chicken, Liver, and Beef", "Chicken, Liver, Beef, Bacon, and Cheese",
            "Chicken, Noodle, and Vegetables", "Chicken, Potato, and Peas", "Chicken, Rice, and Oatmeal",
            "Chicken, Rice, and Turkey", "Chicken, Rice, and Vegetable", "Chicken, Rice, and Vegetables",
            "Chicken, Rice, Beef, Rice, and Cheese", "Chicken, Salmon, and Beef", "Chicken, Salmon, and Egg",
            "Chicken, Salmon, and Tuna", "Chicken, Salmon, and Turkey", "Chicken, Tuna, Catnip, and Seafood",
            "Chicken, Tuna, Dairy, and Seafood", "Chicken, Tuna, Turkey, and Beef", "Chicken, Turkey, and Cheddar",
            "Chunky Chicken and Turkey Stew", "Cod and Shrimp", "Country Stew", "Crab", "Crab and Tuna",
            "Crisp Apple", "Crisp Apple, Chicken and parsley", "Dairy", "Deep Ocean Fish", "Deep Seafood and Fish",
            "Duck", "Duck and Lentils", "Duck and Pea", "Duck and Potato", "Duck and Rice",
            "Egg and Sausage", "Farm-Raised Chicken,Lentils & Sweet Potato Recipe",
            "Farm-Raised Chicken,Rice & Sweet Potato Recipe", "Filet Mignon", "Filet Mignon and Beef",
            "Filet Mignon and New York Strip", "Filet Mignon and Steak", "Filet Mignon Flavor",
            "Filet Mignon, Bacon, and Potato", "Fillet Steak Baked with Dill", "Fish", "Fish and Rice",
            "Fish and Sweet Potato", "Fish and Tuna", "Fish and Vegetable", "Fish, Rice, and Potato",
            "Fish, Whitefish, Tuna, Cod, and Shrimp", "Flavor", "Fresh", "Fresh Liver Flavor", "Freshmint",
            "Fried Lamb Chops with Cauliflower Potato", "Fruit", "Grain Free", "Grandmas Farm Stew with Lamb and Rice",
            "Grass Fed Lamb and Brown Rice Dinner", "Grilled Chicken and NY Strip", "Grilled Chicken Flavor",
            "Grilled Salmon, Rice, and Vegetable", "Grilled Steak and Vegetable", "Hairtail", "Ham",
            "Ham and Egg", "Harvest Potluck with Turkey", "Healthy Chicken and Rice Stew",
            "Healthy Dinner with Lamb and Vegetables", "Healthy Skin and Coat", "Herring", "Herring and Salmon",
            "Herring and Sweet Potato", "Hickory Smoke", "Hickory Smoked BBQ", "Hip and Joint Care", "Holiday Spice",
            "Kangaroo", "Kangaroo and Red Lentils", "Lamb", "Lamb and Lentils", "Lamb and Liver", "Lamb and Potato",
            "Lamb and Rice", "Lamb and Turkey", "Lamb and Vegetables", "Lamb and Venison", "Lamb Meal and Rice",
            "Lamb, Potato, and Peas", "Lamb, Rice, and Vegetable", "Lamb, Vegetables, and Chicken",
            "LID Fish and Potato Recipe", "LID Lamb and Potato Recipe", "LID Turkey and Potato Recipe",
            "Little Yellow Croaker", "Liver", "Liver and Beef", "Lobster", "Mackerel and Whitefish",
            "Meat Lasagna", "Meaty Lamb and Rice Stew", "Milk", "Minced Chicken", "Mint", "Mixed Berry",
            "Mixed Grill", "Multiple Flavors", "New York Strip", "NY Strip", "Oatmeal and Pumpkin",
            "Ocean Fish", "Ocean Fish and Rice", "Ocean Fish and Tuna", "Ocean Whitefish and Tuna", "Original",
            "Original, Fresh, and Beef", "Other", "Peanut", "Peanut Butter", "Peanut Butter and Honey",
            "Poached Salmon", "Pork", "Pork, Potatoes, and Green Beans", "Porterhouse Steak",
            "Porterhouse Steak and Vegetable", "Pot Roast", "Pot Roast and Vegetables", "Potherb and Beef",
            "Poultry", "Prime Rib", "Prime Rib Filet Mignon New York Strip", "Prime Rib, Rice, and Vegetable",
            "Pumpkin Spice", "Real Apple", "Real Banana", "Real Peanut Butter", "Ribeye Steak", "Roasted Chicken",
            "Roasted Lamb, Rice, and Vegetable", "Roasted Turkey and Vegetable Entrée", "Rustic Chicken and Vegetable dinner",
            "Salmon", "Salmon & Trout", "Salmon and Chicken", "Salmon and Egg", "Salmon and Garden Greens",
            "Salmon and Herring", "Salmon and Lentil", "Salmon and Oceanfish", "Salmon and Potato", "Salmon and Red Lentils",
            "Salmon and Rice", "Salmon and Shrimp", "Salmon and Tuna", "Salmon Meal and Sunflower Oil",
            "Salmon, Chicken, and Turkey", "Salmon, Potato, and Peas", "Salmon, Rice, and Vegetable",
            "Salmon, Whitefish, and Tuna", "Salmon,Brown Rice & Sweet Potato Recipe", "Sardines", "Sausage",
            "Sausage, Egg, and Cheese", "Savory Chicken", "Savory Lamb and Garden Variety Entrée", "Seafood",
            "Seafood and Tomato Bisque", "Seafood Medley", "Seafood, Salmon, and Tuna", "Seafood, Salmon, Cod, and Shrimp",
            "Shrimp", "Shrimp and Tuna", "Signature Beef and Potato Entrée", "Silver Fish and Tuna", "Sirloin",
            "Sirloin and Chicken", "Skipjack Tuna", "Smoked Bacon and Cheddar", "Smoked Beef", "Smoked Salmon",
            "Steak", "Steak and Chicken", "Steak and Egg, Chicken, and Liver", "Steak and Eggs", "Steak and Shrimp",
            "Steak and Tuna", "Steak and Vegetable", "Steak, Chicken, and Bacon", "Steak, Egg, and Cheese",
            "Steak, Peas, and Carrots", "Steak, Potatoes, Bacon, and Cheese", "Steamed Fish and Sweet Potato Dinner",
            "Stew", "Tender Beef and Vegetable Recipe", "Tender Chicken and Oatmeal Dinner", "Tender Chicken and Rice Recipe",
            "Tender Chicken and Turkey Recipe", "Tender lamb and Rice Recipe", "Tender Lamb Recipe", "Thunnus Tonggol and Skipjack Tuna",
            "Thunnus Tonggol, Grunion, and Skipjack Tuna", "Trout", "Tuna", "Tuna and Cheese", "Tuna and Chicken",
            "Tuna and Egg", "Tuna and Mackerel", "Tuna and Salmon", "Tuna and Shrimp", "Tuna and Turkey", "Tuna Flavor",
            "Tuna, Chicken, and Salmon", "Tuna, Chicken, and Vegetable", "Tuna, Salmon, and Turkey",
            "Tuna, Salmon, Chicken, and Turkey", "Tuna, Shrimp, and Crab", "Tuna, Shrimp, and Salmon", "Turkey",
            "Turkey and Bacon", "Turkey and Chicken", "Turkey and Cranberry", "Turkey and Giblets", "Turkey and Lamb",
            "Turkey and Liver", "Turkey and Pot Roast", "Turkey and Potato", "Turkey and Rice", "Turkey and Vegetable",
            "Turkey, Green Beans, and Potatoes", "Turkey, Lamb, and Chicken", "Turkey, Potato, and Peas",
            "Turkey, Rice, and Vegetables", "Turkey, Spinach, and Cheese", "Variety", "Vegetable", "Venison",
            "Venison and Green Lentils", "Venison, Rice, and Oatmeal", "Weight Management", "White Fish and Rice",
            "Whitefish", "Whitefish and Tuna", "Wild Blueberry and Pomegranate", "Ocean Fish Excluding Hairball",
            "Seafood Flavor"
    ));

    ArrayList<String> brands = new ArrayList<>(Arrays.asList(
            "Aquarian",
            "Canigou",
            "Catsan",
            "Cesar",
            "Chappi",
            "Chappie",
            "Chum",
            "Corporate",
            "Crave",
            "Dreamies",
            "Dreamies/Temptations",
            "Frolic",
            "Goodlife Recipe",
            "Greenies",
            "Iams",
            "James Wellbeloved",
            "Karma",
            "Kitekat",
            "Koziol",
            "Misfits",
            "Multi-Brand",
            "Nature's Table",
            "Natusan",
            "Nutro",
            "Optimum",
            "Pal",
            "Pedigree",
            "Perfect Fit",
            "Promanage",
            "Sheba",
            "Thomas",
            "Trill",
            "Unbranded",
            "Waltham",
            "Whiskas",
            "Whistle",
            "Wild Frontier",
            "Advance",
            "Schmackos",
            "Dine",
            "My Dog",
            "Spillers",
            "Nuzzle"
    ));

    ArrayList<String> SubBrandNames = new ArrayList<>(Arrays.asList(
            "N/A",
            "Active Fresh",
            "Bianco Fresh",
            "HygienePlus",
            "Natural Clumping",
            "Naturelle",
            "Ultra",
            "Bakies",
            "Bistro",
            "Breakfast & Dinner",
            "Classics",
            "Crunchy",
            "Entrees",
            "Filets",
            "Finest Cuts",
            "Home Delights",
            "Jerky Bites",
            "Meaty Bites",
            "Mini Sticks",
            "Mixed",
            "Mixer",
            "Natural Goodness",
            "NongQingHuaYu",
            "Pal",
            "Poultry Lover's",
            "Puppy",
            "Savory Delights",
            "Simply Crafted",
            "Softies",
            "Steak & Chicken Lovers",
            "Steak & Poultry Lover's",
            "Steak Lover's",
            "Sunrise",
            "Supreme",
            "Temptations",
            "Wet Minis",
            "Wholesome Bowls",
            "Marrowbone & Ancient Grains",
            "Creamy",
            "Meaty Sticks",
            "Mix",
            "Shake Ups",
            "Cheezy Middles",
            "Jumbo Stuff",
            "Mix Ups",
            "Snacky Mouse",
            "Snacky Penguin",
            "Tumblers",
            "Indoor Recipe",
            "Natural",
            "Aging Care",
            "Bites",
            "Dental Chews",
            "Feline Nutrition",
            "Flavor Fusion",
            "Grill Style",
            "Hip & Joint",
            "Jointcare",
            "Jumbone",
            "Natural Balance",
            "OXY2",
            "Pill Pockets",
            "Pockets",
            "Season's Greenies",
            "SmartBites",
            "Supplements",
            "Weight Management",
            "Breed Specific - Bulldog",
            "Breed Specific - Chihuahua",
            "Breed Specific - Dachshund",
            "Breed Specific - German Shepherd",
            "Breed Specific - Labrador Retriever",
            "Breed Specific - Yorkshire Terrier",
            "Chunks",
            "Grain Free Naturals",
            "Grain Free Recipe",
            "Hairball Care",
            "Healthy Adult Original",
            "Healthy Digestion",
            "Healthy Kitten",
            "Healthy Naturals",
            "Healthy Senior",
            "High Protein",
            "Indoor Weight & Hairball Care",
            "Kitten",
            "Large Breed",
            "Lively Senior",
            "Mature Adult",
            "Mature Adult Hairball Care",
            "Minichunks",
            "Multi-Cat Complete",
            "Optimal Metabolism",
            "Optimal Weight",
            "Oral Care Complete",
            "Perfect Portions",
            "Premium Pate",
            "Premium Protection",
            "ProActive",
            "ProActive Health",
            "ProActive Health Hairball",
            "ProActive Health Oral Care",
            "Purrfect Delicacies",
            "Purrfect Delights",
            "Purrfect Grain Free",
            "Senior Plus",
            "Sensitive Naturals",
            "Sensitive Skin & Stomach",
            "Sensitive Stomach",
            "Shakeables",
            "Small & Toy Breed",
            "Smart Puppy",
            "So Good!",
            "Treats",
            "Urinary Tract Health",
            "Woof Delights",
            "Woof Grain Free",
            "Superfoods",
            "1200 Series",
            "Farm’s Harvest",
            "Grain Free",
            "Hearty Stews",
            "Kitchen Classics",
            "Limited Ingredient Diet",
            "Max",
            "Mini Bites",
            "Natural Choice",
            "Natural Choice Complete Care",
            "Ocean",
            "Petite Eats",
            "Premium Loaf",
            "Supremo",
            "Wholesome Essentials",
            "Wild Frontier",
            "Big Dogs",
            "Biscrok",
            "Breathbuster",
            "Butchers Selects",
            "Casseroles",
            "Choice Cuts",
            "Chopped Ground",
            "Chunky Ground",
            "Cuisine",
            "Deep Clean",
            "Dentabone",
            "Dentarask",
            "Dentastix",
            "Dentastix Chewy Chunk",
            "Denta-X",
            "Expert",
            "Healthy Maturity",
            "Healthy Weight",
            "Homestyle Favorites",
            "Little Champions",
            "Marathon",
            "Markies",
            "Marrobites",
            "Marrobone",
            "Mealbone",
            "Mealtime",
            "Meatloaf",
            "Minis",
            "Noodle Bowl",
            "Nutri-Twists",
            "Prime",
            "Professional Nutrition",
            "Protein +",
            "Puppy Dentatubos",
            "Ranchos",
            "Rodeo",
            "Rodeo Duos",
            "Schmackos",
            "Small Dog",
            "Smilers",
            "Sporting Champions",
            "Stackerz",
            "Superchew",
            "Tabs",
            "Tasty Minis",
            "Tender Goodness",
            "Traditional",
            "Trainer",
            "Natural Vitality",
            "Purée",
            "Signature Broths",
            "Tender Sticks",
            "Canine Veterinary Diet",
            "Feline Veterinary Diet",
            "Cat Milk",
            "Cat Treats",
            "Chunky",
            "Crunch",
            "Dentabites",
            "Duo",
            "Favourites",
            "Milky Treats",
            "Perfection",
            "Pure Delight",
            "Purrfectly Chicken",
            "Purrfectly Fish",
            "Seafood Selections",
            "Selection",
            "Specialty Rices",
            "Tasty Mix",
            "Tender Bites",
            "Tender Morsels",
            "Ultramilk",
            "Backyard Cookout",
            "Bacon Feast",
            "Double Delights",
            "Fresh Chef",
            "Creamy Purrr-ee",
            "Vitality Plus"
    ));
    ArrayList<String> AssetCategories = new ArrayList<>(Arrays.asList(
            "3D Renders",
            "Brand Assets",
            "Corporate Assets",
            "Digital",
            "Lighthouse Templating",
            "Print",
            "Sales Materials",
            "Video"
    ));
    ArrayList<String> AssetTypes = new ArrayList<>(Arrays.asList(
            "Labelling/Barcodes",
            "Optimized Images",
            "Packaging",
            "Brand Guidelines",
            "Creative Tools",
            "Logos",
            "Product Images",
            "Toolkits",
            "Documents",
            "Online",
            "Templates",
            "Video",
            "Banners",
            "E-Commerce",
            "Mobile",
            "Signage",
            "Social Content",
            "Website/Microsite",
            "Motion",
            "Static",
            "Ads",
            "Coupon",
            "InStore Merchandising",
            "Film",
            "In Show/Sponsorships",
            "Traditional Online Video Content"
    ));

    ArrayList<String> AssetSubType = new ArrayList<>(Arrays.asList(
            "Feeding Guidelines",
            "GTIN/ Barcode",
            "Guaranteed Analysis",
            "Ingredients",
            "Ingredients/NFP",
            "N/A",
            "Nutrition",
            "Mobile Hero",
            "On Pack Creative",
            "Design Lock",
            "Market Ready",
            "Mechanical",
            "Style Guides",
            "Character",
            "Creative Support Element",
            "Font",
            "Key Visuals",
            "Photography",
            "PPT Template",
            "Recipes",
            "Tagline Asset",
            "Wall Graphic",
            "Logo Elements",
            "Logo Guideline",
            "Logo Variants",
            "Primary Logos",
            "Secondary Logos",
            "Bare Product",
            "Wrapped Product",
            "Primary Asset",
            "Supplemental Assets",
            "Creative Support Elements",
            "Iconography",
            "Illustration",
            "Infographic and Diagrams",
            "M Icon",
            "Purpose",
            "The Five Principles",
            "Code of Conduct",
            "Playbook",
            "Policy",
            "Poster",
            "Press Release",
            "Report",
            "Brand Squares",
            "Internal Identifier",
            "Type 1",
            "Type 2",
            "Type 3",
            "Banners",
            "GIFs",
            "Social Content",
            "Website",
            "Business Stationery",
            "PowerPoint",
            "Word",
            "Brand Purpose",
            "B-Roll",
            "Corporate Essential",
            "Online Video Content",
            "Animated",
            "Static",
            "Brand Equity",
            "Channel",
            "Claims",
            "Count",
            "Enhanced Images",
            "Enhanced Ingredient List",
            "Features and Benefits",
            "Lifestyle",
            "Out of Package",
            "Product Assortment",
            "Size Comparison",
            "Visual Ingredients",
            "Visual Instructions",
            "Application",
            "In App Unit",
            "In-Feed",
            "Reels",
            "Stories",
            "Content Upload",
            "Design/Build",
            "Landing Page",
            "Updates",
            "External",
            "Internal",
            "External Digital",
            "External Print",
            "Internal Digital",
            "Internal Print",
            "Billboards",
            "Place Based",
            "Street Furniture",
            "Transit",
            "POS Collateral",
            "Prepack Display",
            "Cinema: exclusively for Cinema use",
            "TVC",
            "Product Placement",
            "Long Form: Over 1 minute",
            "Short Form: less than 1 minute"
    ));

    ArrayList<String> regions = new ArrayList<>(Arrays.asList(
            "Asia Pacific",
            "Europe",
            "Global",
            "Latin America",
            "Middle East & Africa",
            "North America"
    ));
    ArrayList<String> marketingCountries = new ArrayList<>(Arrays.asList(
            "Asia Pacific",
            "Australia",
            "China",
            "French Polynesia",
            "Hong Kong",
            "India",
            "Indonesia",
            "Japan",
            "Korea",
            "Malaysia",
            "Mongolia",
            "New Caledonia",
            "New Zealand",
            "Papua New Guinea",
            "Philippines",
            "Singapore",
            "Taiwan",
            "Thailand",
            "Vietnam",
            "Albania",
            "Austria",
            "Belgium",
            "Bosnia-Herzegovina",
            "Bulgaria",
            "Croatia",
            "Cyprus",
            "Czech Republic",
            "Denmark",
            "Estonia",
            "Europe",
            "Finland",
            "France",
            "Germany",
            "Greece",
            "Hungary",
            "Iceland",
            "Ireland",
            "Italy",
            "Kosovo",
            "Latvia",
            "Lithuania",
            "Macedonia",
            "Moldova",
            "Montenegro",
            "Netherlands",
            "Norway",
            "Poland",
            "Portugal",
            "Romania",
            "Serbia",
            "Slovak Republic",
            "Slovenia",
            "Spain",
            "Sweden",
            "Switzerland",
            "Ukraine",
            "United Kingdom",
            "Global",
            "Mars ITR",
            "Argentina",
            "Brazil",
            "Chile",
            "Colombia",
            "Costa Rica",
            "Dominican Republic",
            "Ecuador",
            "Guatemala",
            "Latin America",
            "Mexico",
            "Panama",
            "Peru",
            "Puerto Rico",
            "Venezuela",
            "Algeria",
            "Angola",
            "Armenia",
            "Azerbaijan",
            "Bahrain",
            "Belarus",
            "Benin",
            "Botswana",
            "Congo",
            "Djibouti",
            "Egypt",
            "Ethiopia",
            "Georgia",
            "Ghana",
            "Iraq",
            "Israel",
            "Ivory Coast",
            "Jordan",
            "Kazakhstan",
            "Kenya",
            "Kuwait",
            "Kyrgyzstan",
            "Lebanon",
            "Libya",
            "Middle East & Africa",
            "Morocco",
            "Mozambique",
            "Namibia",
            "Nigeria",
            "Oman",
            "Qatar",
            "Russia",
            "Rwanda",
            "Saudi Arabia",
            "Senegal",
            "Sierra Leone",
            "South Africa",
            "Sudan",
            "Syria",
            "Tajikistan",
            "Tanzania",
            "Tunisia",
            "Turkey",
            "Turkmenistan",
            "Uganda",
            "United Arab Emirates",
            "Uzbekistan",
            "Yemen",
            "Zimbabwe",
            "Canada",
            "North America",
            "United States"
    ));
    ArrayList<String> originatingCountries = new ArrayList<>(Arrays.asList(
            "United States",
            "United Kingdom",
            "Canada",
            "China",
            "Poland",
            "Germany",
            "France",
            "Brazil",
            "Mexico",
            "New Zealand",
            "Australia",
            "Japan",
            "Russia",
            "Korea",
            "Philippines",
            "Argentina",
            "India",
            "Ukraine",
            "Ireland",
            "Chile",
            "Malaysia",
            "Puerto Rico",
            "Thailand",
            "Colombia",
            "Italy",
            "Belgium",
            "Greece",
            "Asia Pacific",
            "Taiwan",
            "North America",
            "Spain",
            "Europe",
            "Hong Kong",
            "Global",
            "Netherlands",
            "Denmark",
            "Portugal",
            "Sweden",
            "N/A"
    ));

}
